# Generated by Django 2.1.5 on 2019-02-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LPC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='bet_win',
            field=models.BooleanField(),
        ),
    ]
